before_script:
    - set

julia_version:
    image: staticfloat/binarybuilder.jl:v0.6-master
    script:
        - julia -e 'versioninfo()'
        - ls -la
        - pwd
        - julia --color=yes build_tarballs.jl --verbose

